# Generated by Django 4.1.7 on 2023-02-20 23:16

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PackageComposition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "package_composition",
            },
        ),
        migrations.CreateModel(
            name="PackageContact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.SmallIntegerField(choices=[(0, "이메일"), (1, "휴대폰 번호")])),
                ("content", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "package_contact",
            },
        ),
        migrations.CreateModel(
            name="SurveyPackage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("logo", models.ImageField(null=True, upload_to="user_profiles/")),
                ("access_code", models.CharField(max_length=10)),
                (
                    "uuid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None, length=22, max_length=22, prefix=""
                    ),
                ),
                ("is_closed", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=200)),
                ("manager", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "survey_package",
            },
        ),
    ]
