# Generated by Django 4.1.7 on 2023-03-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        ("surveys", "0001_initial"),
        ("survey_packages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="respondent",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="packagesubjectsurvey",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to="survey_packages.packagesubject",
            ),
        ),
        migrations.AddField(
            model_name="packagesubjectsurvey",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_content",
                to="surveys.survey",
            ),
        ),
        migrations.AddField(
            model_name="packagesubject",
            name="package_part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="survey_packages.packagepart",
            ),
        ),
        migrations.AddField(
            model_name="packagepart",
            name="survey_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="survey_packages.surveypackage",
            ),
        ),
        migrations.AddField(
            model_name="packagecontact",
            name="survey_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="survey_packages.surveypackage",
            ),
        ),
    ]
