# Generated by Django 4.1.7 on 2023-02-20 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("surveys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("survey_packages", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveypackage",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="surveypackage",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="packagecontact",
            name="survey_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="survey_packages.surveypackage",
            ),
        ),
        migrations.AddField(
            model_name="packagecomposition",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surveys.survey"
            ),
        ),
        migrations.AddField(
            model_name="packagecomposition",
            name="survey_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="survey_packages.surveypackage",
            ),
        ),
    ]
