# Generated by Django 4.1.7 on 2023-02-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0001_initial"),
        ("survey_packages", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveypackage",
            name="logo",
            field=models.ImageField(null=True, upload_to="package_logo/"),
        ),
        migrations.RemoveField(
            model_name="surveypackage",
            name="workspace",
        ),
        migrations.AddField(
            model_name="surveypackage",
            name="workspace",
            field=models.ManyToManyField(null=True, to="workspaces.workspace"),
        ),
    ]
