# Generated by Django 4.1.7 on 2023-02-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_routine_kick_off_workspace_access_code_and_more"),
        ("surveys", "0002_initial"),
        ("survey_packages", "0003_alter_surveypackage_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackagePart",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "package_part",
            },
        ),
        migrations.CreateModel(
            name="PackageSubject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                (
                    "package_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_packages.packagepart",
                    ),
                ),
            ],
            options={
                "db_table": "package_subject",
            },
        ),
        migrations.AlterField(
            model_name="packagecontact",
            name="type",
            field=models.SmallIntegerField(
                choices=[("email", "이메일"), ("phone", "휴대폰 번호")]
            ),
        ),
        migrations.AlterField(
            model_name="surveypackage",
            name="workspace",
            field=models.ManyToManyField(
                null=True, related_name="packages", to="workspaces.workspace"
            ),
        ),
        migrations.CreateModel(
            name="PackageSubjectSurvey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_packages.packagesubject",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surveys.survey"
                    ),
                ),
            ],
            options={
                "db_table": "package_subject_survey",
            },
        ),
        migrations.AddField(
            model_name="packagepart",
            name="survey_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="survey_packages.surveypackage",
            ),
        ),
    ]
