# Generated by Django 4.1.7 on 2023-02-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_routine_kick_off_workspace_access_code_and_more"),
        ("surveys", "0003_alter_sectorchoice_sector_and_more"),
        (
            "survey_packages",
            "0004_packagepart_packagesubject_alter_packagecontact_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagepart",
            name="survey_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="survey_packages.surveypackage",
            ),
        ),
        migrations.AlterField(
            model_name="packagesubject",
            name="package_part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="survey_packages.packagepart",
            ),
        ),
        migrations.AlterField(
            model_name="packagesubjectsurvey",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to="survey_packages.packagesubject",
            ),
        ),
        migrations.AlterField(
            model_name="packagesubjectsurvey",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_content",
                to="surveys.survey",
            ),
        ),
        migrations.AlterField(
            model_name="surveypackage",
            name="workspace",
            field=models.ManyToManyField(
                related_name="packages", to="workspaces.workspace"
            ),
        ),
    ]
