# Generated by Django 4.1.7 on 2023-03-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("survey_packages", "0005_alter_packagepart_survey_package_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagecontact",
            name="survey_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="survey_packages.surveypackage",
            ),
        ),
        migrations.AlterField(
            model_name="packagecontact",
            name="type",
            field=models.CharField(
                choices=[("email", "이메일"), ("phone", "휴대폰 번호")], max_length=10
            ),
        ),
    ]
