# Generated by Django 4.1.7 on 2023-03-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey_packages", "0006_alter_packagecontact_survey_package_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagesubject",
            name="number",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="packagesubjectsurvey",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
