# Generated by Django 4.1.7 on 2023-03-04 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey_packages", "0006_alter_packagecontact_type"),
        ("survey_packages", "0007_packagesubject_number_packagesubjectsurvey_title"),
    ]

    operations = []
