# Generated by Django 4.1.7 on 2023-03-04 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey_packages", "0008_merge_20230304_0852"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveypackage",
            name="workspace",
        ),
    ]
