# Generated by Django 4.1.7 on 2023-03-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey_packages", "0009_remove_surveypackage_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagesubjectsurvey",
            name="number",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
