# Generated by Django 4.1.7 on 2023-03-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0005_alter_routine_workspace"),
        ("survey_packages", "0010_packagesubjectsurvey_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Respondent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("respondent_id", models.CharField(max_length=30)),
                (
                    "survey_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="survey_packages.surveypackage",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "respondent",
            },
        ),
    ]
