# Generated by Django 4.1.7 on 2023-03-09 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey_packages", "0011_respondent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PackageComposition",
        ),
    ]
