version: '3.8'
services:
    db:
      image: mysql:latest
      container_name: convey-db
      ports:
        - "3306:3306"
      command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        - convey-mysql:/var/lib/mysql
        - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        TZ: Asia/Seoul

volumes:
  convey-mysql: