# Generated by Django 4.1.7 on 2023-02-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "admin"), (1, "subject")], default=0, editable=False
            ),
        ),
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=10)),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "admin"), (1, "subject")],
                        default=1,
                        editable=False,
                    ),
                ),
                ("social_provider", models.CharField(default="kakao", max_length=15)),
            ],
            options={
                "db_table": "app_user",
                "unique_together": {("email",)},
            },
        ),
    ]
