# Generated by Django 4.1.7 on 2023-02-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_role_appuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AppUser",
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="user",
            name="social_provider",
            field=models.PositiveSmallIntegerField(choices=[(0, "kakao")], null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "admin"), (1, "subject")], editable=False
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("email", "role")},
        ),
    ]
