# Generated by Django 4.1.7 on 2023-02-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_delete_appuser_alter_user_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="social_provider",
            field=models.CharField(
                choices=[("kakao", "kakao")], max_length=15, null=True
            ),
        ),
    ]
