# Generated by Django 4.1.7 on 2023-02-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_social_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "admin"), (1, "subject")]
            ),
        ),
    ]
