# Generated by Django 4.1.7 on 2023-03-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="privacy_policy_agreed",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
