# Generated by Django 4.1.7 on 2023-03-09 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0001_initial"),
        ("survey_packages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("abbr", models.CharField(max_length=5)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "survey",
            },
        ),
        migrations.CreateModel(
            name="SurveySector",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("likert", "리커트"),
                            ("short_answer", "단답형"),
                            ("single_select", "단일 선택"),
                            ("multi_select", "다중 선택"),
                            ("extent", "정도"),
                            ("long_answer", "서술형"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "db_table": "survey_sector",
            },
        ),
        migrations.CreateModel(
            name="SectorQuestion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("number", models.FloatField()),
                ("content", models.CharField(max_length=200)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "linked_sector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_sector",
                        to="surveys.surveysector",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="surveys.surveysector",
                    ),
                ),
            ],
            options={
                "db_table": "sector_question",
            },
        ),
        migrations.CreateModel(
            name="QuestionChoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("number", models.PositiveIntegerField()),
                ("content", models.CharField(max_length=200, null=True)),
                ("is_descriptive", models.BooleanField()),
                ("desc_form", models.CharField(max_length=50, null=True)),
                (
                    "related_question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="surveys.sectorquestion",
                    ),
                ),
                (
                    "related_sector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="common_choices",
                        to="surveys.surveysector",
                    ),
                ),
            ],
            options={
                "db_table": "question_choice",
            },
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("respondent_id", models.CharField(max_length=30)),
                ("answer", models.CharField(max_length=500)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.sectorquestion",
                    ),
                ),
                (
                    "survey_package",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="survey_packages.surveypackage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "question_answer",
            },
        ),
    ]
