# Generated by Django 4.1.7 on 2023-02-20 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("survey_packages", "0002_initial"),
        ("surveys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="sectorquestion",
            name="linked_sector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_sector",
                to="surveys.surveysector",
            ),
        ),
        migrations.AddField(
            model_name="sectorquestion",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surveys.surveysector"
            ),
        ),
        migrations.AddField(
            model_name="sectorchoice",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surveys.surveysector"
            ),
        ),
        migrations.AddField(
            model_name="respondent",
            name="survey_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="survey_packages.surveypackage",
            ),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="surveys.sectorquestion",
            ),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
