# Generated by Django 4.1.7 on 2023-02-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectorchoice",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="surveys.surveysector",
            ),
        ),
        migrations.AlterField(
            model_name="sectorquestion",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="surveys.surveysector",
            ),
        ),
        migrations.AlterField(
            model_name="surveysector",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("likert", "리커트"),
                    ("short_answer", "단답형"),
                    ("single_select", "단일 선택"),
                    ("multi_select", "다중 선택"),
                    ("extent", "정도"),
                    ("long_answer", "서술형"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="surveysector",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sectors",
                to="surveys.survey",
            ),
        ),
    ]
