# Generated by Django 4.1.7 on 2023-03-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_alter_questionanswer_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectorquestion",
            name="is_required",
        ),
        migrations.RemoveField(
            model_name="sectorquestion",
            name="linked_sector",
        ),
        migrations.AddField(
            model_name="surveysector",
            name="is_linked",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
