# Generated by Django 4.1.7 on 2023-02-28 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0003_alter_sectorchoice_sector_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sectorchoice",
            unique_together={("sector", "key", "value")},
        ),
    ]
