# Generated by Django 4.1.7 on 2023-03-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0003_remove_sectorquestion_is_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveysector",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="surveysector",
            name="title",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
