# Generated by Django 4.1.7 on 2023-03-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0004_alter_sectorchoice_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoicesSet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "choices_set",
            },
        ),
        migrations.CreateModel(
            name="QuestionChoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("number", models.PositiveIntegerField()),
                ("content", models.CharField(max_length=200, null=True)),
                ("is_descriptive", models.BooleanField()),
                ("desc_form", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "question_choice",
            },
        ),
        migrations.DeleteModel(
            name="SectorChoice",
        ),
        migrations.AddField(
            model_name="choicesset",
            name="choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="surveys.questionchoice",
            ),
        ),
        migrations.AddField(
            model_name="choicesset",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices_set",
                to="surveys.sectorquestion",
            ),
        ),
    ]
