# Generated by Django 4.1.7 on 2023-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0004_alter_surveysector_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveysector",
            name="title",
        ),
        migrations.AddField(
            model_name="surveysector",
            name="instruction",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="surveysector",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
