# Generated by Django 4.1.7 on 2023-03-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0005_remove_surveysector_title_surveysector_instruction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveysector",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="surveysector",
            name="instruction",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
