# Generated by Django 4.1.7 on 2023-03-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0006_questionchoice_related_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectorquestion",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
