# Generated by Django 4.1.7 on 2023-03-04 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0005_alter_routine_workspace"),
        ("surveys", "0008_questionanswer_survey_package_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionanswer",
            name="subject",
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workspaces.workspace",
            ),
        ),
    ]
