# Generated by Django 4.1.7 on 2023-03-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0009_remove_questionanswer_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswer",
            name="answer",
            field=models.CharField(max_length=500),
        ),
    ]
