# Generated by Django 4.1.7 on 2023-02-20 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("survey_packages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Routine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("duration", models.IntegerField()),
            ],
            options={
                "db_table": "routine",
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workspace",
            },
        ),
        migrations.CreateModel(
            name="WorkspaceComposition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "survey_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_packages.surveypackage",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_composition",
            },
        ),
        migrations.CreateModel(
            name="RoutineDetail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nth_day", models.PositiveSmallIntegerField()),
                ("time", models.CharField(max_length=5)),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.routine",
                    ),
                ),
                (
                    "survey_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_packages.surveypackage",
                    ),
                ),
            ],
            options={
                "db_table": "routine_detail",
            },
        ),
        migrations.AddField(
            model_name="routine",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workspaces.workspace"
            ),
        ),
    ]
