# Generated by Django 4.1.7 on 2023-04-01 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("survey_packages", "0003_alter_packagesubjectsurvey_number_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routinedetail",
            name="external_resource",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="routinedetail",
            name="survey_package",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey_packages.surveypackage",
            ),
        ),
    ]
