# Generated by Django 4.1.7 on 2023-03-04 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_routine_kick_off_workspace_access_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="uuid",
            field=models.CharField(default="8DvpHx54j8uGJBmMGnATHi", max_length=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="routinedetail",
            name="routine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routines",
                to="workspaces.routine",
            ),
        ),
    ]
