# Generated by Django 4.1.7 on 2023-03-04 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0003_workspace_uuid_alter_routinedetail_routine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacecomposition",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_packages",
                to="workspaces.workspace",
            ),
        ),
    ]
