# Generated by Django 4.1.7 on 2023-03-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0004_alter_workspacecomposition_workspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="workspace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routine",
                to="workspaces.workspace",
            ),
        ),
    ]
